FROM python:3.7.10-buster

WORKDIR /app

COPY . /app

RUN pip install --no-cache-dir -r requirements.txt
RUN mkdir -p logs
RUN mkdir -p trades
RUN mkdir -p src/hist_data

CMD ["python" , "main.py", "skalpit"]