FROM python:3.9.2-buster

WORKDIR /app

COPY . /app

RUN pip install --no-cache-dir -r requirements.txt
RUN mkdir -p logs
RUN mkdir -p trades
RUN mkdir -p hist_data

ENTRYPOINT ["python3" , "main.py", "backtester", "2021-03-02" , "2021-03-12"]